//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winRef.WsEcollect {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.avisortech.com/eCollectWebservices", ConfigurationName="WsEcollect.eCollectWebservicesv3Soap")]
    public interface eCollectWebservicesv3Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/getTransactionInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        winRef.WsEcollect.getTransactionInformationResponseType getTransactionInformation(winRef.WsEcollect.getTransactionInformationType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/getTransactionInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<winRef.WsEcollect.getTransactionInformationResponseType> getTransactionInformationAsync(winRef.WsEcollect.getTransactionInformationType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/getBankList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        winRef.WsEcollect.getBankListResponseType[] getBankList(winRef.WsEcollect.getBankListType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/getBankList", ReplyAction="*")]
        System.Threading.Tasks.Task<winRef.WsEcollect.getBankListResponseType[]> getBankListAsync(winRef.WsEcollect.getBankListType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/createTransactionPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        winRef.WsEcollect.createTransactionResponseType createTransactionPayment(winRef.WsEcollect.createTransactionType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/createTransactionPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<winRef.WsEcollect.createTransactionResponseType> createTransactionPaymentAsync(winRef.WsEcollect.createTransactionType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/processTransactionPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        winRef.WsEcollect.getTransactionInformationResponseType processTransactionPayment(winRef.WsEcollect.createTransactionType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/processTransactionPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<winRef.WsEcollect.getTransactionInformationResponseType> processTransactionPaymentAsync(winRef.WsEcollect.createTransactionType request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class getTransactionInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityCodeField;
        
        private string ticketIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
                this.RaisePropertyChanged("EntityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TicketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("TicketId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class createTransactionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnCodeField;
        
        private string ticketIdField;
        
        private string eCollectUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TicketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("TicketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string eCollectUrl {
            get {
                return this.eCollectUrlField;
            }
            set {
                this.eCollectUrlField = value;
                this.RaisePropertyChanged("eCollectUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class subserviceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityCodeField;
        
        private string srvCodeField;
        
        private string valueTypeField;
        
        private decimal transValueField;
        
        private decimal transVatValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
                this.RaisePropertyChanged("EntityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SrvCode {
            get {
                return this.srvCodeField;
            }
            set {
                this.srvCodeField = value;
                this.RaisePropertyChanged("SrvCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
                this.RaisePropertyChanged("ValueType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal TransValue {
            get {
                return this.transValueField;
            }
            set {
                this.transValueField = value;
                this.RaisePropertyChanged("TransValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal TransVatValue {
            get {
                return this.transVatValueField;
            }
            set {
                this.transVatValueField = value;
                this.RaisePropertyChanged("TransVatValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class itemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemCodeField;
        
        private string flagDBCRField;
        
        private int itemQtyField;
        
        private string itemDescField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
                this.RaisePropertyChanged("ItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FlagDBCR {
            get {
                return this.flagDBCRField;
            }
            set {
                this.flagDBCRField = value;
                this.RaisePropertyChanged("FlagDBCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ItemQty {
            get {
                return this.itemQtyField;
            }
            set {
                this.itemQtyField = value;
                this.RaisePropertyChanged("ItemQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
                this.RaisePropertyChanged("ItemDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class createTransactionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityCodeField;
        
        private string srvCodeField;
        
        private decimal transValueField;
        
        private decimal transVatValueField;
        
        private string srvCurrencyField;
        
        private string uRLResponseField;
        
        private string uRLRedirectField;
        
        private string signField;
        
        private string signFieldsField;
        
        private string[] referenceArrayField;
        
        private string paymentSystemField;
        
        private string fICodeField;
        
        private string invoiceField;
        
        private string policyCodeField;
        
        private string[] authReferenceArrayField;
        
        private itemType[] itemArrayField;
        
        private subserviceType[] subservicesArrayField;
        
        private AdditionalInfoType[] additionalInfoArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
                this.RaisePropertyChanged("EntityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SrvCode {
            get {
                return this.srvCodeField;
            }
            set {
                this.srvCodeField = value;
                this.RaisePropertyChanged("SrvCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TransValue {
            get {
                return this.transValueField;
            }
            set {
                this.transValueField = value;
                this.RaisePropertyChanged("TransValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal TransVatValue {
            get {
                return this.transVatValueField;
            }
            set {
                this.transVatValueField = value;
                this.RaisePropertyChanged("TransVatValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SrvCurrency {
            get {
                return this.srvCurrencyField;
            }
            set {
                this.srvCurrencyField = value;
                this.RaisePropertyChanged("SrvCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string URLResponse {
            get {
                return this.uRLResponseField;
            }
            set {
                this.uRLResponseField = value;
                this.RaisePropertyChanged("URLResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string URLRedirect {
            get {
                return this.uRLRedirectField;
            }
            set {
                this.uRLRedirectField = value;
                this.RaisePropertyChanged("URLRedirect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("Sign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SignFields {
            get {
                return this.signFieldsField;
            }
            set {
                this.signFieldsField = value;
                this.RaisePropertyChanged("SignFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceArray", Order=9)]
        public string[] ReferenceArray {
            get {
                return this.referenceArrayField;
            }
            set {
                this.referenceArrayField = value;
                this.RaisePropertyChanged("ReferenceArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PaymentSystem {
            get {
                return this.paymentSystemField;
            }
            set {
                this.paymentSystemField = value;
                this.RaisePropertyChanged("PaymentSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FICode {
            get {
                return this.fICodeField;
            }
            set {
                this.fICodeField = value;
                this.RaisePropertyChanged("FICode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PolicyCode {
            get {
                return this.policyCodeField;
            }
            set {
                this.policyCodeField = value;
                this.RaisePropertyChanged("PolicyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public string[] AuthReferenceArray {
            get {
                return this.authReferenceArrayField;
            }
            set {
                this.authReferenceArrayField = value;
                this.RaisePropertyChanged("AuthReferenceArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemArray", Order=15)]
        public itemType[] ItemArray {
            get {
                return this.itemArrayField;
            }
            set {
                this.itemArrayField = value;
                this.RaisePropertyChanged("ItemArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubservicesArray", Order=16)]
        public subserviceType[] SubservicesArray {
            get {
                return this.subservicesArrayField;
            }
            set {
                this.subservicesArrayField = value;
                this.RaisePropertyChanged("SubservicesArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInfoArray", Order=17)]
        public AdditionalInfoType[] AdditionalInfoArray {
            get {
                return this.additionalInfoArrayField;
            }
            set {
                this.additionalInfoArrayField = value;
                this.RaisePropertyChanged("AdditionalInfoArray");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class AdditionalInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string infoCodeField;
        
        private string infoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InfoCode {
            get {
                return this.infoCodeField;
            }
            set {
                this.infoCodeField = value;
                this.RaisePropertyChanged("InfoCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InfoData {
            get {
                return this.infoDataField;
            }
            set {
                this.infoDataField = value;
                this.RaisePropertyChanged("InfoData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class getBankListResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paymentSystemField;
        
        private string financialInstitutionCodeField;
        
        private string financialInstitutionNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string paymentSystem {
            get {
                return this.paymentSystemField;
            }
            set {
                this.paymentSystemField = value;
                this.RaisePropertyChanged("paymentSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string financialInstitutionCode {
            get {
                return this.financialInstitutionCodeField;
            }
            set {
                this.financialInstitutionCodeField = value;
                this.RaisePropertyChanged("financialInstitutionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string financialInstitutionName {
            get {
                return this.financialInstitutionNameField;
            }
            set {
                this.financialInstitutionNameField = value;
                this.RaisePropertyChanged("financialInstitutionName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class getBankListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
                this.RaisePropertyChanged("EntityCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class retriesTicketIdType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ticketIdField;
        
        private string tranStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TicketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("TicketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TranState {
            get {
                return this.tranStateField;
            }
            set {
                this.tranStateField = value;
                this.RaisePropertyChanged("TranState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class operationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string operCodeField;
        
        private string flagDBCRField;
        
        private string operDescField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OperCode {
            get {
                return this.operCodeField;
            }
            set {
                this.operCodeField = value;
                this.RaisePropertyChanged("OperCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FlagDBCR {
            get {
                return this.flagDBCRField;
            }
            set {
                this.flagDBCRField = value;
                this.RaisePropertyChanged("FlagDBCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OperDesc {
            get {
                return this.operDescField;
            }
            set {
                this.operDescField = value;
                this.RaisePropertyChanged("OperDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class getTransactionInformationResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityCodeField;
        
        private string ticketIdField;
        
        private string trazabilityCodeField;
        
        private string tranStateField;
        
        private string returnCodeField;
        
        private decimal transValueField;
        
        private decimal transVatValueField;
        
        private string payCurrencyField;
        
        private decimal currencyRateField;
        
        private System.DateTime bankProcessDateField;
        
        private string fICodeField;
        
        private string bankNameField;
        
        private string paymentSystemField;
        
        private string transCycleField;
        
        private string invoiceField;
        
        private string[] referenceArrayField;
        
        private string[] authReferenceArrayField;
        
        private operationType[] operationArrayField;
        
        private retriesTicketIdType[] retriesTicketIdField;
        
        private AdditionalInfoType[] additionalInfoArrayField;
        
        private string srvCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
                this.RaisePropertyChanged("EntityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TicketId {
            get {
                return this.ticketIdField;
            }
            set {
                this.ticketIdField = value;
                this.RaisePropertyChanged("TicketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TrazabilityCode {
            get {
                return this.trazabilityCodeField;
            }
            set {
                this.trazabilityCodeField = value;
                this.RaisePropertyChanged("TrazabilityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TranState {
            get {
                return this.tranStateField;
            }
            set {
                this.tranStateField = value;
                this.RaisePropertyChanged("TranState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal TransValue {
            get {
                return this.transValueField;
            }
            set {
                this.transValueField = value;
                this.RaisePropertyChanged("TransValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal TransVatValue {
            get {
                return this.transVatValueField;
            }
            set {
                this.transVatValueField = value;
                this.RaisePropertyChanged("TransVatValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PayCurrency {
            get {
                return this.payCurrencyField;
            }
            set {
                this.payCurrencyField = value;
                this.RaisePropertyChanged("PayCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal CurrencyRate {
            get {
                return this.currencyRateField;
            }
            set {
                this.currencyRateField = value;
                this.RaisePropertyChanged("CurrencyRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime BankProcessDate {
            get {
                return this.bankProcessDateField;
            }
            set {
                this.bankProcessDateField = value;
                this.RaisePropertyChanged("BankProcessDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FICode {
            get {
                return this.fICodeField;
            }
            set {
                this.fICodeField = value;
                this.RaisePropertyChanged("FICode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
                this.RaisePropertyChanged("BankName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PaymentSystem {
            get {
                return this.paymentSystemField;
            }
            set {
                this.paymentSystemField = value;
                this.RaisePropertyChanged("PaymentSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TransCycle {
            get {
                return this.transCycleField;
            }
            set {
                this.transCycleField = value;
                this.RaisePropertyChanged("TransCycle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceArray", Order=15)]
        public string[] ReferenceArray {
            get {
                return this.referenceArrayField;
            }
            set {
                this.referenceArrayField = value;
                this.RaisePropertyChanged("ReferenceArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public string[] AuthReferenceArray {
            get {
                return this.authReferenceArrayField;
            }
            set {
                this.authReferenceArrayField = value;
                this.RaisePropertyChanged("AuthReferenceArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperationArray", Order=17)]
        public operationType[] OperationArray {
            get {
                return this.operationArrayField;
            }
            set {
                this.operationArrayField = value;
                this.RaisePropertyChanged("OperationArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RetriesTicketId", Order=18)]
        public retriesTicketIdType[] RetriesTicketId {
            get {
                return this.retriesTicketIdField;
            }
            set {
                this.retriesTicketIdField = value;
                this.RaisePropertyChanged("RetriesTicketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInfoArray", Order=19)]
        public AdditionalInfoType[] AdditionalInfoArray {
            get {
                return this.additionalInfoArrayField;
            }
            set {
                this.additionalInfoArrayField = value;
                this.RaisePropertyChanged("AdditionalInfoArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SrvCode {
            get {
                return this.srvCodeField;
            }
            set {
                this.srvCodeField = value;
                this.RaisePropertyChanged("SrvCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface eCollectWebservicesv3SoapChannel : winRef.WsEcollect.eCollectWebservicesv3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eCollectWebservicesv3SoapClient : System.ServiceModel.ClientBase<winRef.WsEcollect.eCollectWebservicesv3Soap>, winRef.WsEcollect.eCollectWebservicesv3Soap {
        
        public eCollectWebservicesv3SoapClient() {
        }
        
        public eCollectWebservicesv3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public eCollectWebservicesv3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eCollectWebservicesv3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eCollectWebservicesv3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public winRef.WsEcollect.getTransactionInformationResponseType getTransactionInformation(winRef.WsEcollect.getTransactionInformationType request) {
            return base.Channel.getTransactionInformation(request);
        }
        
        public System.Threading.Tasks.Task<winRef.WsEcollect.getTransactionInformationResponseType> getTransactionInformationAsync(winRef.WsEcollect.getTransactionInformationType request) {
            return base.Channel.getTransactionInformationAsync(request);
        }
        
        public winRef.WsEcollect.getBankListResponseType[] getBankList(winRef.WsEcollect.getBankListType request) {
            return base.Channel.getBankList(request);
        }
        
        public System.Threading.Tasks.Task<winRef.WsEcollect.getBankListResponseType[]> getBankListAsync(winRef.WsEcollect.getBankListType request) {
            return base.Channel.getBankListAsync(request);
        }
        
        public winRef.WsEcollect.createTransactionResponseType createTransactionPayment(winRef.WsEcollect.createTransactionType request) {
            return base.Channel.createTransactionPayment(request);
        }
        
        public System.Threading.Tasks.Task<winRef.WsEcollect.createTransactionResponseType> createTransactionPaymentAsync(winRef.WsEcollect.createTransactionType request) {
            return base.Channel.createTransactionPaymentAsync(request);
        }
        
        public winRef.WsEcollect.getTransactionInformationResponseType processTransactionPayment(winRef.WsEcollect.createTransactionType request) {
            return base.Channel.processTransactionPayment(request);
        }
        
        public System.Threading.Tasks.Task<winRef.WsEcollect.getTransactionInformationResponseType> processTransactionPaymentAsync(winRef.WsEcollect.createTransactionType request) {
            return base.Channel.processTransactionPaymentAsync(request);
        }
    }
}
